name: "{{name}} - Django CI"
type: ci
triggers:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  - name: "test"
    runsOn: "ubuntu-latest"
    timeout: 30
    strategy:
      matrix:
        python-version: {{toYamlArray pythonVersions}}
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
      
      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "{{packageManager}}"
      
      - name: "Install dependencies"
        run: "{{installCommand}}"
      
      - name: "Run database migrations"
        run: "{{virtualEnvSetup}} && python manage.py migrate"
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test_db"
          DJANGO_SETTINGS_MODULE: "{{projectName}}.settings.test"
          SECRET_KEY: "test-secret-key-for-ci"
        if: "{{isDjango}}"
      
      - name: "Collect static files"
        run: "{{buildCommand}}"
        env:
          DJANGO_SETTINGS_MODULE: "{{projectName}}.settings.test"
          SECRET_KEY: "test-secret-key-for-ci"
        if: "{{isDjango}} && {{buildCommand}}"
      
      - name: "Run linting"
        run: "{{lintCommand}}"
        if: "{{hasLinting}}"
      
      - name: "Run type checking"
        run: "{{typeCheckCommand}}"
        if: "{{hasTypeChecking}}"
      
      - name: "Run tests"
        run: "{{testCommand}}"
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test_db"
          DJANGO_SETTINGS_MODULE: "{{projectName}}.settings.test"
          SECRET_KEY: "test-secret-key-for-ci"
      
      - name: "Upload coverage reports"
        uses: "codecov/codecov-action@v4"
        if: "{{hasCoverage}}"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
          file: "./coverage.xml"
          fail_ci_if_error: false