name: "{{name}} - Python CI"
type: ci
triggers:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  - name: "test"
    runsOn: "ubuntu-latest"
    timeout: 30
    strategy:
      matrix:
        python-version: {{toYamlArray pythonVersions}}
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
      
      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "{{packageManager}}"
      
      - name: "Install dependencies"
        run: "{{installCommand}}"
      
      - name: "Run linting"
        run: "{{lintCommand}}"
        if: "{{hasLinting}}"
      
      - name: "Run type checking"
        run: "{{typeCheckCommand}}"
        if: "{{hasTypeChecking}}"
      
      - name: "Run tests"
        run: "{{testCommand}}"
        env:
          PYTHONPATH: "."
          PYTHONDONTWRITEBYTECODE: "1"
      
      - name: "Upload coverage reports"
        uses: "codecov/codecov-action@v4"
        if: "{{hasCoverage}}"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
          file: "./coverage.xml"
          fail_ci_if_error: false