name: Integration Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  integration-validation:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run type checking
      run: npm run type-check
    
    - name: Run unit tests
      run: npm run test:unit
    
    - name: Run integration validation
      run: npm run validate:integration
    
    - name: Run integration tests
      run: npm run test:integration
    
    - name: Run performance tests
      run: npm run test:performance
    
    - name: Build project
      run: npm run build:fast
    
    - name: Upload integration validation report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-validation-report-node-${{ matrix.node-version }}
        path: integration-validation-report.json
        retention-days: 30
    
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-coverage-node-${{ matrix.node-version }}
        path: coverage/
        retention-days: 30

  build-validation:
    runs-on: ubuntu-latest
    needs: integration-validation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run full CI pipeline
      run: npm run ci
    
    - name: Verify build artifacts
      run: |
        if [ ! -d "dist" ]; then
          echo "Build artifacts not found"
          exit 1
        fi
        
        if [ ! -f "dist/index.js" ]; then
          echo "Main build artifact not found"
          exit 1
        fi
        
        if [ ! -f "dist/index.d.ts" ]; then
          echo "Type definitions not found"
          exit 1
        fi
        
        echo "Build artifacts verified successfully"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
        retention-days: 30

  integration-matrix:
    runs-on: ${{ matrix.os }}
    needs: integration-validation
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run integration validation (cross-platform)
      run: npm run validate:integration
    
    - name: Run core integration tests
      run: npm run test:integration -- tests/integration/component-initialization.test.ts
    
    - name: Upload platform-specific report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-report-${{ matrix.os }}-node-${{ matrix.node-version }}
        path: integration-validation-report.json
        retention-days: 7